### ISSUE TITLE
error occured with vgit

### ISSUE THREAD

**Issue by fgheng** [Shatur/neovim-session-manager#37] opened 2022-05-04 08:07 UTC
**Bug description**

Error occured while I use `SessionManager load_session`
```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...er/opt/vgit.nvim/lua/vgit/features/buffer/LiveGutter.lua:34: In
valid buffer id: 8
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:39>
```
**Steps to reproduce**

<details><summary>Minimal configuration</summary>
</details>

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/50551377/166643861-940f5a58-2ca2-4a2c-adff-a9a7bf8ce01b.png)

**Environment**

- OS: arch linux
- Desktop environment: gnome
- Plugins commit hash: 

**Additional context**

**Comment by Shatur** [comment] 2022-05-04 08:17
Duplicate of #36.

**Closed by Shatur** 2022-05-04 08:17 UTC
Labels: bug
