### ISSUE TITLE
Error detected while processing VimEnter Autocommands for "*"..VimEnter Autocommands for "*"

### ISSUE THREAD

**Issue by rafisics** [Shatur/neovim-session-manager#130] opened 2024-06-13 11:07 UTC
**Bug description**
Updating `neovim-session-manager` from commit a0b9d25154be573bc0f99877afb3f57cf881cce7 to 29f80e9c6f3620b81908e287b3d1ed79c2290dd5 } is giving the following error when I am opening neovim. 

```
Error detected while processing VimEnter Autocommands for "*"..VimEnter Autocommands for "*":
Error executing lua callback: ...lazy/neovim-session-manager/lua/session_manager/init.lua:111: attempt to call field 'isarray' (a nil value)
stack traceback:
        ...lazy/neovim-session-manager/lua/session_manager/init.lua:111: in function <...lazy/neovim-session-manager/lua/session_manager/init.lua:105>
        [C]: in function 'nvim_exec_autocmds'
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:157: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:156>
        [C]: in function 'xpcall'
        .../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:156: in function '_trigger'
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:139: in function 'trigger'
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:87: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:72>
Press ENTER or type command to continue

```

**Environment**
```
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
```
- OS: Ubuntu
- Desktop environment: Gnome
- Plugins commit hash: 29f80e9c6f3620b81908e287b3d1ed79c2290dd5

**Comment by Shatur** [comment] 2024-06-13 11:39
Duplicate of #129.

**Closed by Shatur** 2024-06-13 11:39 UTC
Labels: bug
