### ISSUE TITLE
'winheight' cannot be small er than 'winminheight

### ISSUE THREAD

**Issue by towry** [Shatur/neovim-session-manager#66] opened 2022-12-06 18:17 UTC
**Bug description**

```
Error executing vim.schedule lua callback: ...art/neovim-session-manager/lua/session_manager/utils.lua:82: Vim(set):E591: 'winheight' cannot be small
er than 'winminheight': winheight=1                                                                                                                  
stack traceback:                                                                                                                                     
        [C]: in function 'nvim_command'                                                                                                              
        ...art/neovim-session-manager/lua/session_manager/utils.lua:82: in function <...art/neovim-session-manager/lua/session_manager/utils.lua:70> 
```

Press ENTER or type command to continue        

**Steps to reproduce**

<details><summary>Minimal configuration</summary>

</details>

**Expected behavior**

**Screenshots**

**Environment**

- OS: 
- Desktop environment: 
- Plugins commit hash: 

**Additional context**

https://github.com/pze/nvim/blob/4eadc9013d2aaefee67d17d22883e57a8ab0fa27/lua/overlays/rc/session_tw_.lua#L1

**Comment by Shatur** [comment] 2022-12-06 18:19
Duplicate of #47.

**Closed as completed by Shatur** 2022-12-06 18:19 UTC
Labels: bug
